function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
end

function on_message(self, message_id, message, sender)
	print(message_id)
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("Touch!")
		msg.post("/NPC", "gather", {x = action.x, y = action.y, r = 100})
	end
end
