local spawning_cars_time = 2
go.property("number", 0)

function add_car(self)
	position = go.get_position(".")
	position.z = 0.65
	car = factory.create("main:/cars#factory", position, nil, {Color = 0}, 1.0)
	local navigator = msg.url("main", "/navigator", "")
	msg.post(car, "start", {from = self.number, to = nil, navigator = navigator})
end

function init(self)
	timer.delay(spawning_cars_time, true, function() add_car(self) end)
end
