function init(self)
	msg.post("#sprite", "disable")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("showField") then
		msg.post("#sprite", "enable")
	elseif message_id == hash("hideField") then
		msg.post("#sprite", "disable")
	elseif message_id == hash("disableCO") then
		msg.post("#collisionobject", "disable")
	elseif message_id == hash("enableCO") then
		msg.post("#collisionobject", "enable")		
end
